name: temple_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_screenutil: ^5.9.3
  google_translation: ^1.0.0
  pinput: ^5.0.2
  translator: ^1.0.4+1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  marquee: ^2.3.0
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  audioplayers: ^6.5.1
  syncfusion_flutter_pdfviewer: ^32.1.22
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  youtube_player_flutter: ^9.1.3
  shimmer: ^3.0.0
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ABeeZee
      fonts:
        - asset: fonts/ABeeZee-Regular.ttf
        - asset: fonts/ABeeZee-Italic.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf

  assets:
    - assets/images/
    - assets/images/dashboard/
    - assets/images/background/
    - assets/images/about/
    - assets/images/live_seva/
    - assets/audio/
    - assets/pdfs/
    
